# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43235f426cc463fd1fff56d53808cc8936c088feff043a27979eebd8595887d2517f4dd4798b9f5b0ca17a7c20b9efceadf9de8e984b645a96e15e05e60a69d7

test:
  secret_key_base: 093fc1405a388049ab48dd7678568f4e88eadf58bbb8ab104ddfc3060ed7f97b023a9bd25b111ebd1252175c328043a3244213a715f1bea778fb88c91035cc68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
